---
title: "Plotting Supplementary Model results"
author: "Ruben J, Hermann"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(patchwork)
```

```{r}
data <- read.csv("../../Data/Model Results/Population dynamics_P0.9_Kc1.csv")
inf <- read.csv("../../Data/Model Results/Summarized results_P0.9_Kc1.csv")
data2 <- read.csv("../../Data/Model Results/Population dynamics_P0.8_Kc2.csv")
inf2 <- read.csv("../../Data/Model Results/Summarized results_P0.8_Kc2.csv")

data_p <- subset(data,time<21)
data_p$trait_dist=0

for (i in 1:nrow(data_p)){
  for (j in 1:nrow(inf)){
    if(data_p$run[i]==inf$run[j] & data_p$start_freq[i]==inf$start_freq[j])
    {data_p$trait_dist[i] <- inf$trait_dist[j]}
  }
}
data_p$start_freq <- as.factor(data_p$star_freq)

data2_p <- subset(data,time<21)
data2_p$trait_dist=0

for (i in 1:nrow(data2_p)){
  for (j in 1:nrow(inf2)){
    if(data2_p$run[i]==inf2$run[j] & data2_p$start_freq[i]==inf2$start_freq[j])
    {data2_p$trait_dist[i] <- inf2$trait_dist[j]}
  }
}
data2_p$start_freq <- as.factor(data2_p$start_freq)

```

Creating Figure S8

```{r}
##############################################################################
#For max trait distance Kc1=1 p1=0.9
p1<-ggplot(subset(data_p,trait_dist==max(data_p$trait_dist)),aes(x=time,y=(C1+C2),color=start_freq))+
  geom_line(size=3)+
  theme_classic()+
  ylim(c(0,0.5))+
  ggtitle("Kc1=1 & p1=0.9 + Kc2=8 & p2=0.2")+
  ylab("Total prey density 10^5 cells/ml")+ xlab("Time")+
  labs(color = 'Starting freq of defended clone')

p2<-ggplot(subset(data_p,trait_dist==max(data_p$trait_dist)),aes(x=time,y=(B+S),color=start_freq))+
  geom_line(size=3)+
  theme_classic()+
  ylim(c(0,20))+
  ggtitle("Kc1=1 & p1=0.9 + Kc2=8 & p2=0.2")+
  ylab("Total predator density")+ xlab("Time")+
  labs(color = 'Starting freq of defended clone')


p3<-ggplot(subset(data_p,trait_dist==max(data_p$trait_dist)),aes(x=time,y=(1-freq_def),color=start_freq))+
  geom_line(size=3)+
  theme_classic()+
  ylim(c(0,1))+
  ggtitle("Kc1=1 & p1=0.9 + Kc2=8 & p2=0.2")+
  ylab("Frequency of undefended clone")+ xlab("Time")+
  labs(color = 'Starting freq of defended clone')

p4<-ggplot(subset(data_p,trait_dist==max(data_p$trait_dist)),aes(x=time,y=geb,color=start_freq))+
  geom_line(size=3)+
  theme_classic()+
  #ylim(c(-6,6))+
  ggtitle("Kc1=1 & p1=0.9 + Kc2=8 & p2=0.2")+
  ylab("ln(Evolution/Ecology)")+ xlab("Time")+
  labs(color = 'Starting freq of defended clone')



figure <- p2+p1+p3+p4+guide_area()+plot_layout(ncol=2)
ggsave("../../Figures/S8.pdf",figure,width=25,height=30,limitsize = FALSE)

```

```{r}
ggplot()

```
